In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Project_DataSets02.csv")
df.head()

,Doctor_Name,Specialization,Exprience,Hospital_Name,City,Patient_Like,Info_Source,Consultation_Fee
0,Dr. Anil Krishna Gundala,Cardiologist,23,Medicover Hospitals,Hyderabad,96.0,Practo,800
1,Dr. Sai Ravi Shanker A,Cardiologist,31,Aster Prime Hospital,Hyderabad,60.0,Practo,800
2,Dr. R. Balaji,Cardiologist,37,Medicover Hospitals,Hyderabad,97.0,Practo,900
3,Dr. Krishna Prasad A R,Cardiologist,32,Medicover Hospitals,Hyderabad,82.0,Practo,800
4,Dr. Shiva Prasad Koyalakonda,Cardiologist,23,One Cardiac Centre,Hyderabad,93.0,Practo,700

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Doctor_Name       1080 non-null   object
 1   Specialization    1080 non-null   object
 2   Exprience         1080 non-null   int64
 3   Hospital_Name     1080 non-null   object
 4   City              1080 non-null   object
 5   Patient_Like      1080 non-null   float64
 6   Info_Source       1080 non-null   object
 7   Consultation_Fee  1080 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 67.6+ KB

In [4]:
metro = ["Hyderabad", "Bangalore", "Chennai", "Kolkata", "Mumbai", "Delhi"]
city_type = []

for city in df["City"]:
    
    if city in metro:
        city_type.append("Metro")
        
    else:
        city_type.append("Non-Metro")

In [5]:
df.insert(df.columns.get_loc("City")+1, "City_Tier", city_type)

In [6]:
df.head()

,Doctor_Name,Specialization,Exprience,Hospital_Name,City,City_Tier,Patient_Like,Info_Source,Consultation_Fee
0,Dr. Anil Krishna Gundala,Cardiologist,23,Medicover Hospitals,Hyderabad,Metro,96.0,Practo,800
1,Dr. Sai Ravi Shanker A,Cardiologist,31,Aster Prime Hospital,Hyderabad,Metro,60.0,Practo,800
2,Dr. R. Balaji,Cardiologist,37,Medicover Hospitals,Hyderabad,Metro,97.0,Practo,900
3,Dr. Krishna Prasad A R,Cardiologist,32,Medicover Hospitals,Hyderabad,Metro,82.0,Practo,800
4,Dr. Shiva Prasad Koyalakonda,Cardiologist,23,One Cardiac Centre,Hyderabad,Metro,93.0,Practo,700

In [7]:
df[df["City"] =="Delhi"]

,Doctor_Name,Specialization,Exprience,Hospital_Name,City,City_Tier,Patient_Like,Info_Source,Consultation_Fee
30,Dr. Sanjiv Gupta,Cardiologist,27,Metro Hospital and Cancer Institute,Delhi,Metro,97.0,Practo,1500
31,Dr. Ramesh Raikar,Cardiologist,34,RLKC Hospital & Metro Heart Institute,Delhi,Metro,100.0,Practo,1200
32,Dr. Ajay Aggarwal,Cardiologist,25,Yatharth Super Speciality Hospital,Delhi,Metro,83.0,Practo,1500
33,Dr. Navjeet Singh Ahluwalia,Cardiologist,37,Kalra Hospitals,Delhi,Metro,33.0,Practo,1000
34,Dr. Nishant Verma,Cardiologist,20,Cygnus MLS Superspecility Hospital,Delhi,Metro,50.0,Practo,500
...,...,...,...,...,...,...,...,...,...
981,Dr. Arun Jain,Orthopedist,41,Muni Maya Ram Jain Hospital,Delhi,Metro,92.0,Practo,500
982,Dr. Mandeep Singh,Orthopedist,26,SCI International Hospital,Delhi,Metro,86.0,Practo,1500
983,Dr. Himanshu Gupta,Orthopedist,19,Center For Sports Injury,Delhi,Metro,95.0,Practo,1000
984,Dr. Abhishek Kumar Mishra,Orthopedist,29,MASSH,Delhi,Metro,97.0,Practo,1200
985,Dr. Shuvendu Prosad Roy,Orthopedist,28,Aashlok Hospital,Delhi,Metro,75.0,Practo,1000

In [8]:
df.rename(columns={
    "Patient_Like": "Patient_Rating(%)",
    "Info_Source": "Source",
    "Consultation_Fee": "Consultation_Fee(₹)",
    "Exprience": "Experience"
}, inplace=True)

In [9]:
df.head()

,Doctor_Name,Specialization,Experience,Hospital_Name,City,City_Tier,Patient_Rating(%),Source,Consultation_Fee(₹)
0,Dr. Anil Krishna Gundala,Cardiologist,23,Medicover Hospitals,Hyderabad,Metro,96.0,Practo,800
1,Dr. Sai Ravi Shanker A,Cardiologist,31,Aster Prime Hospital,Hyderabad,Metro,60.0,Practo,800
2,Dr. R. Balaji,Cardiologist,37,Medicover Hospitals,Hyderabad,Metro,97.0,Practo,900
3,Dr. Krishna Prasad A R,Cardiologist,32,Medicover Hospitals,Hyderabad,Metro,82.0,Practo,800
4,Dr. Shiva Prasad Koyalakonda,Cardiologist,23,One Cardiac Centre,Hyderabad,Metro,93.0,Practo,700

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Doctor_Name          1080 non-null   object
 1   Specialization       1080 non-null   object
 2   Experience           1080 non-null   int64
 3   Hospital_Name        1080 non-null   object
 4   City                 1080 non-null   object
 5   City_Tier            1080 non-null   object
 6   Patient_Rating(%)    1080 non-null   float64
 7   Source               1080 non-null   object
 8   Consultation_Fee(₹)  1080 non-null   int64
dtypes: float64(1), int64(2), object(6)
memory usage: 76.1+ KB

In [10]:
df.to_csv("Practo_DataSets.csv", index=False)